# -*- coding: utf-8 -*-
"""h_w10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cNt-JDrVqAfEdfi2y3DExEqHMnHEqjz5

##Задача 44:
В ячейке ниже представлен код генерирующий DataFrame, которая состоит всего из 1 столбца. 
Ваша задача перевести его в one hot вид. Сможете ли вы это сделать без get_dummies?
"""

import pandas as pd
import seaborn as sns
import random

lst = ['robot'] * 5
lst += ['human'] * 5
random.shuffle(lst)
data = pd.DataFrame({'whoAmI': lst})
data.head()

data.loc[data['whoAmI'] == 'robot', 'robot'] = int(1)
data.loc[data['whoAmI'] != 'robot', 'robot'] = int(0)
data.loc[data['whoAmI'] == 'human', 'human'] = int(1)
data.loc[data['whoAmI'] != 'human', 'human'] = int(0)
data[['robot', 'human']]
